### ISSUE TITLE
Fix: projen-renovate TypeScript import error after schema regeneration

### ISSUE THREAD

**Issue by langri-sha** [langri-sha/langri-sha.com#1013]
## Context

After merging PR #1012 (fix pnpm lockfile), CI is now failing on the `check / Lint` step with a TypeScript compilation error in `packages/projen-renovate`.

## Error

```
packages/projen-renovate/src/index.ts(3,15): error TS2724: '"./renovate"' has no exported member named 'JSONSchemaForRenovate42931ConfigFilesHttpsRenovatebotCom'. Did you mean 'JSONSchemaForRenovate431320ConfigFilesHttpsRenovatebotCom'?
```

## Root Cause

The renovate schema type was regenerated (likely via `schemastore-to-typescript`) and the type name changed:
- Old: `JSONSchemaForRenovate42931ConfigFilesHttpsRenovatebotCom`
- New: `JSONSchemaForRenovate431320ConfigFilesHttpsRenovatebotCom`

The import in `packages/projen-renovate/src/index.ts` wasn't updated to match.

## Goal

Fix the TypeScript import to use the correct, current type name from the generated renovate.d.ts file.

## Acceptance Criteria

- [ ] Update import in `packages/projen-renovate/src/index.ts` to use the correct type name
- [ ] Run `pnpm projen` to regenerate any affected project files
- [ ] Verify `pnpm lint` passes locally
- [ ] Create beachball change file
- [ ] CI passes on next run

## Technical Notes

- Run `pnpm run change` to create a change file
- This is a breaking change for consumers of the projen-renovate package
- The type name change appears to be automatic based on schema version
